[profile.default]
src = "src"
out = "artifacts"
libs = [".dev/@openzeppelin", "lib"]

remappings = [
    "@openzeppelin/=.deps/npm/@openzeppelin/",
]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
